name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd site
        npm install
      working-directory: naodigital-reto1

    - name: Run site tests
      run: |
        cd site
        npx react-scripts test
      working-directory: naodigital-reto1




