name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Debug info
      run: |
        pwd
        ls -la
        cd site
        pwd
        ls -la

    - name: Install global react-scripts
      run: npm install -g react-scripts

    - name: Install site dependencies
      working-directory: site
      run: npm install

    - name: Run site tests
      working-directory: site
      run: npm test



