name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install API Dependencies
      run: |
        cd api
        npm install

    - name: Run API Tests
      run: |
        cd api
        npm test

    - name: Serverless Deploy
      run: |
        cd api
        npx serverless deploy

  build_site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Site Dependencies
      run: |
        cd site
        npm install

    - name: Check package.json
      run: |
        cd site
        cat package.json

    - name: Debugging
      run: |
        pwd
        ls

    - name: Run Site Tests
      run: |
        cd site
        npm test

    - name: Build Site
      run: |
        cd site
        npm run build






